on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Build and Deploy
      run: |
        cd public/
        python render.py
        cd ..

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: public
        path: public/
